name = "OpenStreetMapXPlot"
uuid = "d3d4fdd0-c191-11e8-3358-a3629b56487d"
authors = ["Przemyslaw Szufel <pszufe@gmail.com>", "Bartosz Pankratz <bartosz.pankratz@gmail.com>", "Anna Szczurek <annaszczurek2@gmail.com>", "Bogumil Kaminski <bogumil.kaminski@gmail.com>", "Pawel Pralat <pralat@ryerson.ca>"]
version = "0.1.0"

[deps]
OpenStreetMapX = "5c67c38e-c187-11e8-2be6-e3a6a3a5610f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
